### ISSUE TITLE
feat: don't generate opensource related files for non-oss projects

### ISSUE THREAD

**Issue by martinm82** [tomtom-international/cookiecutter-python#52]
### Description

Right now regardless whether a project is published on GH or BB we produce the same files. Some files are important when opensourcing a project whereas for internal usage only some are superfluous.

The idea is that when selecting BitBucket Server as VCS we can assume that the project won't be opensourced. In that case we should clean up all files related to OSS in the post hook.

If someone decides to opensource the projects the template can be again applied with GH as VCS and the important files will be generated again.

**Comment by AKhranovskiy** [comment]
The following files could be removed in case of BitBucket setup:
* CHANGELOG.md + docs/history.rst - commit log should be enough for internal use
* AUTHORS + docs/authors.rst - it would be one or few teams rather to people, can be infer from commit log
* LICENSE - internal project may have specific license

**Comment by martinm82** [comment]
Thanks for the contribution @AKhranovskiy
